### ISSUE TITLE
Auth - Add more info to users.

### ISSUE THREAD

**Issue by luigilgue** [pablotabares/decide#52]
We need the fields Sex and Age. 

It will be perfect to add this fields so we can show some percentages relatives to the census and participation.

**Comment by Wordsan** [comment]
how is this going? I'm filtering data in the census app. I can do more filters with that values if you've added it to the model.

**Comment by alvarogonjim** [comment]
Hello @Wordsan my colleage didn't do this issue so I started to do it. The model User can't be modified so I create a new model (DecideUser) with the attributes that you need, sex and birthday.
I started working on the branch `ortosia-auth-model-decideuser` I will merge to the base branch `ortosia-auth` and finally to the preproduction.

In order to make it easy for you I'll give you an endpoint that will return the data that you need like in the image
![call](https://user-images.githubusercontent.com/25668523/51044315-1b282d00-15c1-11e9-9a79-8c85771c4081.png)
